export const GET_PUBLICATIONS = 'GET_PUBLICATIONS_PROFILE'
export const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_PROFILE_SUCCESS'
export const GET_PUBLICATIONS_FAIL = 'GET_PUBLICATIONS_PROFILE_FAIL'

export const LIKE_PUBLICATIONS_PROFILE = 'LIKE_PUBLICATIONS_PROFILE'
export const LIKE_PUBLICATIONS_PROFILE_SUCCESS = 'LIKE_PUBLICATIONS_PROFILE_SUCCESS'
export const LIKE_PUBLICATIONS_PROFILE_FAIL = 'LIKE_PUBLICATIONS_PROFILE_FAIL'

export const UNLIKE_PUBLICATIONS_PROFILE = 'UNLIKE_PUBLICATIONS_PROFILE'
export const UNLIKE_PUBLICATIONS_PROFILE_SUCCESS = 'UNLIKE_PUBLICATIONS_PROFILE_SUCCESS'
export const UNLIKE_PUBLICATIONS_PROFILE_FAIL = 'UNLIKE_PUBLICATIONS_PROFILE_FAIL'

export const UPDATE_COMMENT_PUBLICATIONS_PROFILE_SUCCESS = 'UPDATE_COMMENT_PUBLICATIONS_PROFILE_SUCCESS'

export const RESET_PUBLICATIONS = 'RESET_PUBLICATIONS_PROFILE'
