export const GET_PAGE = 'GET_PAGE';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_FAIL = 'GET_PAGE_FAIL';

export const UNFOLLOW_PAGE = 'UNFOLLOW_PAGE';
export const UNFOLLOW_PAGE_SUCCESS = 'UNFOLLOW_PAGE_SUCCESS';
export const UNFOLLOW_PAGE_FAIL = 'UNFOLLOW_PAGE_FAIL';

export const FOLLOW_PAGE = 'FOLLOW_PAGE';
export const FOLLOW_PAGE_SUCCESS = 'FOLLOW_PAGE_SUCCESS';
export const FOLLOW_PAGE_FAIL = 'FOLLOW_PAGE_FAIL';
