export const GET_ROOM_BY_ID = 'GET_ROOM_BY_ID'
export const GET_ROOM_BY_ID_SUCCESS = 'GET_ROOM_BY_ID_SUCCESS'
export const GET_ROOM_BY_ID_FAIL = 'GET_ROOM_BY_ID_FAIL'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const REST_ROOM = 'REST_ROOM'
export const LOAD_OLD_MESSAGE_SUCCESS = 'LOAD_OLD_MESSAGE_SUCCESS'

