export const GET_ROOM_BY_ID = 'GET_ROOM_BY_ID'
export const GET_ROOM_BY_ID_SUCCESS = 'GET_ROOM_BY_ID_SUCCESS'
export const GET_ROOM_BY_ID_FAIL = 'GET_ROOM_BY_ID_FAIL'

export const LOAD_MORE_MESSAGE_BY_ID = 'LOAD_MORE_MESSAGE_BY_ID'
export const LOAD_MORE_MESSAGE_BY_ID_SUCCESS = 'LOAD_MORE_MESSAGE_BY_ID_SUCCESS'
export const LOAD_MORE_MESSAGE_BY_ID_FAIL = 'LOAD_MORE_MESSAGE_BY_ID_FAIL'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const RESET_ROOM = 'RESET_ROOM'
export const LOAD_OLD_MESSAGE_SUCCESS = 'LOAD_OLD_MESSAGE_SUCCESS'
export const UPDATE_OPEN_ROOM = 'UPDATE_OPEN_ROOM'