export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const SET_UP_LANGUAGE_CONFIG = 'SET_UP_LANGUAGE_CONFIG'

export const FORGOT_PASSWORD_SEND = 'FORGOT_PASSWORD_SEND'
export const FORGOT_PASSWORD_SEND_SUCCESS = 'FORGOT_PASSWORD_SEND_SUCCESS'
export const FORGOT_PASSWORD_SEND_FAIL = 'FORGOT_PASSWORD_SEND_FAIL'

export const LOGOUT = 'LOGOUT'
export const RESET_USER_CONNECTED = 'RESET_USER_CONNECTED'