export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL'

export const DELETE_NOTIFICATION_BY_ID = 'DELETE_NOTIFICATION_BY_ID'
export const DELETE_NOTIFICATION_BY_ID_SUCCESS = 'DELETE_NOTIFICATION_BY_ID_SUCCESS'
export const DELETE_NOTIFICATION_BY_ID_FAIL = 'DELETE_NOTIFICATION_BY_ID_FAIL'

export const REFRESH_NOTIFICATIONS = 'REFRESH_NOTIFICATIONS'
export const REFRESH_NOTIFICATIONS_SUCCESS = 'REFRESH_NOTIFICATIONS_SUCCESS'
export const REFRESH_NOTIFICATIONS_FAIL = 'REFRESH_NOTIFICATIONS_FAIL'

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS'

export const PUT_VIEW_ON_NOTIFICATION_BY_ID = 'PUT_VIEW_ON_NOTIFICATION_BY_ID'