export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const ASK_FRIEND = 'ASK_FRIEND';
export const ASK_FRIEND_SUCCESS = 'ASK_FRIEND_SUCCESS';
export const ASK_FRIEND_FAIL = 'ASK_FRIEND_FAIL';

export const CANCEL_ASK_FRIEND = 'CANCEL_ASK_FRIEND';
export const CANCEL_ASK_FRIEND_SUCCESS = 'CANCEL_ASK_FRIEND_SUCCESS';
export const CANCEL_ASK_FRIEND_FAIL = 'CANCEL_ASK_FRIEND_FAIL';

export const UNFOLLOW_PROFILE = 'UNFOLLOW_PROFILE';
export const UNFOLLOW_PROFILE_SUCCESS = 'UNFOLLOW_PROFILE_SUCCESS';
export const UNFOLLOW_PROFILE_FAIL = 'UNFOLLOW_PROFILE_FAIL';

export const FOLLOW_PROFILE = 'FOLLOW_PROFILE';
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS';
export const FOLLOW_PROFILE_FAIL = 'FOLLOW_PROFILE_FAIL';

export const CONFIRM_FRIEND = 'CONFIRM_FRIEND';
export const CONFIRM_FRIEND_SUCCESS = 'CONFIRM_FRIEND_SUCCESS';
export const CONFIRM_FRIEND_FAIL = 'CONFIRM_FRIEND_FAIL';