export const ADD_PUBLICATIONS_PENDING = 'ADD_PUBLICATIONS_PENDING'
export const ADD_PUBLICATIONS_PENDING_SUCCESS = 'ADD_PUBLICATIONS_PENDING_SUCCESS'
export const ADD_PUBLICATIONS_PENDING_FAIL = 'ADD_PUBLICATIONS_PENDING_FAIL'

export const DELETE_ITEM_IN_PENDING_LIST = 'DELETE_ITEM_IN_PENDING_LIST'
export const CANCEL_PUBLICATION = 'CANCEL_PUBLICATION'