export const GET_PUBLICATIONS = 'GET_PUBLICATIONS'
export const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_SUCCESS'
export const GET_PUBLICATIONS_FAIL = 'GET_PUBLICATIONS_FAIL'

export const REFRESH_PUBLICATIONS = 'REFRESH_PUBLICATIONS'
export const REFRESH_PUBLICATIONS_SUCCESS = 'REFRESH_PUBLICATIONS_SUCCESS'
export const REFRESH_PUBLICATIONS_FAIL = 'REFRESH_PUBLICATIONS_FAIL'

export const LIKE_PUBLICATIONS_FEED = 'LIKE_PUBLICATIONS_FEED'
export const LIKE_PUBLICATIONS_FEED_SUCCESS = 'LIKE_PUBLICATIONS_FEED_SUCCESS'
export const LIKE_PUBLICATIONS_FEED_FAIL = 'LIKE_PUBLICATIONS_FEED_FAIL'

export const ADD_PUBLICATIONS_FEED = 'ADD_PUBLICATIONS_FEED'
export const ADD_PUBLICATIONS_FEED_SUCCESS = 'ADD_PUBLICATIONS_FEED_SUCCESS'
export const ADD_PUBLICATIONS_FEED_FAIL = 'ADD_PUBLICATIONS_FEED_FAIL'

export const UNLIKE_PUBLICATIONS_FEED = 'UNLIKE_PUBLICATIONS_FEED'
export const UNLIKE_PUBLICATIONS_FEED_SUCCESS = 'UNLIKE_PUBLICATIONS_FEED_SUCCESS'
export const UNLIKE_PUBLICATIONS_FEED_FAIL = 'UNLIKE_PUBLICATIONS_FEED_FAIL'

export const UPDATE_COMMENT_PUBLICATIONS_FEED_SUCCESS = 'UPDATE_COMMENT_PUBLICATIONS_FEED_SUCCESS'

export const RESET_PUBLICATIONS = 'RESET_PUBLICATIONS'
