export const PUT_PUBLICATION_IN_MODAL = 'PUT_PUBLICATION_IN_MODAL'
export const RESET_PUBLICATIONS_IN_MODAL = 'RESET_PUBLICATIONS_IN_MODAL'

export const GET_FEED_PUBLICATION_BY_ID_START = 'GET_FEED_PUBLICATION_BY_ID_START'
export const GET_FEED_PUBLICATION_BY_ID_SUCCESS = 'GET_FEED_PUBLICATION_BY_ID_SUCCESS'
export const GET_FEED_PUBLICATION_BY_ID_FAIL = 'GET_FEED_PUBLICATION_BY_ID_FAIL'
