export const GET_PUBLICATIONS = 'GET_PUBLICATIONS_DISCOVER'
export const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_DISCOVER_SUCCESS'
export const GET_PUBLICATIONS_FAIL = 'GET_PUBLICATIONS_DISCOVER_FAIL'

export const LIKE_PUBLICATIONS_DISCOVER = 'LIKE_PUBLICATIONS_DISCOVER'
export const LIKE_PUBLICATIONS_DISCOVER_SUCCESS = 'LIKE_PUBLICATIONS_DISCOVER_SUCCESS'
export const LIKE_PUBLICATIONS_DISCOVER_FAIL = 'LIKE_PUBLICATIONS_DISCOVER_FAIL'

export const UNLIKE_PUBLICATIONS_DISCOVER = 'UNLIKE_PUBLICATIONS_DISCOVER'
export const UNLIKE_PUBLICATIONS_DISCOVER_SUCCESS = 'UNLIKE_PUBLICATIONS_DISCOVER_SUCCESS'
export const UNLIKE_PUBLICATIONS_DISCOVER_FAIL = 'UNLIKE_PUBLICATIONS_DISCOVER_FAIL'

export const UPDATE_COMMENT_PUBLICATIONS_DISCOVER_SUCCESS = 'UPDATE_COMMENT_PUBLICATIONS_DISCOVER_SUCCESS'

export const RESET_PUBLICATIONS = 'RESET_PUBLICATIONS_DISCOVER'
