export const GET_TUBE_PAGE = 'GET_TUBE_PAGE';
export const GET_TUBE_PAGE_SUCCESS = 'GET_TUBE_PAGE_SUCCESS';
export const GET_TUBE_PAGE_FAIL = 'GET_TUBE_PAGE_FAIL';

export const LIKE_TUBE_PAGE = 'LIKE_TUBE_PAGE';
export const LIKE_TUBE_PAGE_SUCCESS = 'LIKE_TUBE_PAGE_SUCCESS';
export const LIKE_TUBE_PAGE_FAIL = 'LIKE_TUBE_PAGE_FAIL';

export const DISLIKE_TUBE_PAGE = 'DISLIKE_TUBE_PAGE';
export const DISLIKE_TUBE_PAGE_SUCCESS = 'DISLIKE_TUBE_PAGE_SUCCESS';
export const DISLIKE_TUBE_PAGE_FAIL = 'DISLIKE_TUBE_PAGE_FAIL';

export const FOLLOW_IN_TUBE_PAGE = 'FOLLOW_IN_TUBE_PAGE';
export const FOLLOW_IN_TUBE_PAGE_SUCCESS = 'FOLLOW_IN_TUBE_PAGE_SUCCESS';
export const FOLLOW_IN_TUBE_PAGE_FAIL = 'FOLLOW_IN_TUBE_PAGE_FAIL';

export const UNFOLLOW_IN_TUBE_PAGE = 'UNFOLLOW_IN_TUBE_PAGE';
export const UNFOLLOW_IN_TUBE_PAGE_SUCCESS = 'UNFOLLOW_IN_TUBE_PAGE_SUCCESS';
export const UNFOLLOW_IN_TUBE_PAGE_FAIL = 'UNFOLLOW_IN_TUBE_PAGE_FAIL';

export const RESET_TUBE_PAGE = 'RESET_TUBE_PAGE';
