export const GET_COMMENT_LIST = 'GET_COMMENT_LIST'
export const GET_COMMENT_LIST_SUCCESS = 'GET_COMMENT_LIST_SUCCESS'
export const GET_COMMENT_LIST_FAIL = 'GET_COMMENT_LIST_FAIL'

export const SEND_COMMENT = 'SEND_COMMENT'
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL'

export const LIKE_COMMENT = 'LIKE_COMMENT'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL'

export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'
export const UNLIKE_COMMENT_SUCCESS = 'UNLIKE_COMMENT_SUCCESS'
export const UNLIKE_COMMENT_FAIL = 'UNLIKE_COMMENT_FAIL'

export const RESET_COMMENT_LIST = 'RESET_COMMENT_LIST'
