export const GET_STORIES = 'GET_STORIES'
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS'
export const GET_STORIES_FAIL = 'GET_STORIES_FAIL'

export const GET_STACK = 'GET_STACK'
export const GET_STACK_SUCCESS = 'GET_STACK_SUCCESS'
export const GET_STACK_FAIL = 'GET_STACK_FAIL'

export const REFRESH_STORIES = 'REFRESH_STORIES'
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS'
export const REFRESH_STORIES_FAIL = 'REFRESH_STORIES_FAIL'

export const RESET_STORIES = 'RESET_STORIES'
export const RESET_STACK = 'RESET_STACK'
export const MOVE_TO_PREVIOUS_STACK = 'MOVE_TO_PREVIOUS_STACK'
export const STORY_SEEN = 'STORY_SEEN'