export const GET_MUSIC_PLAYLIST = 'GET_MUSIC_PLAYLIST'
export const GET_MUSIC_PLAYLIST_SUCCESS = 'GET_MUSIC_PLAYLIST_SUCCESS'
export const GET_MUSIC_PLAYLIST_FAIL = 'GET_MUSIC_PLAYLIST_FAIL'

export const SET_MUSIC_PLAYLIST_IN_CACHE = 'SET_MUSIC_PLAYLIST_IN_CACHE'
export const SET_MUSIC_PLAYLIST_IN_CACHE_SUCCESS = 'SET_MUSIC_PLAYLIST_IN_CACHE_SUCCESS'
export const SET_MUSIC_PLAYLIST_IN_CACHE_FAIL = 'SET_MUSIC_PLAYLIST_IN_CACHE_FAIL'

export const LIKE_MUSIC_FROM_PLAYER = 'LIKE_MUSIC_FROM_PLAYER'
export const LIKE_MUSIC = 'LIKE_MUSIC'
export const LIKE_MUSIC_SUCCESS = 'LIKE_MUSIC_SUCCESS'
export const LIKE_MUSIC_FAIL = 'LIKE_MUSIC_FAIL'

export const DISLIKE_MUSIC = 'DISLIKE_MUSIC'
export const DISLIKE_MUSIC_SUCCESS = 'DISLIKE_MUSIC_SUCCESS'
export const DISLIKE_MUSIC_FAIL = 'DISLIKE_MUSIC_FAIL'

export const START_OF_UPLOAD_PLAYLIST = 'START_OF_UPLOAD_PLAYLIST'
export const END_OF_UPLOAD_PLAYLIST = 'END_OF_UPLOAD_PLAYLIST'
export const RESET_MUSIC_PLAYLIST = 'RESET_MUSIC_PLAYLIST'