export const GET_MUSIC_MENU = 'GET_MUSIC_MENU';
export const GET_MUSIC_MENU_SUCCESS = 'GET_MUSIC_MENU_SUCCESS';
export const GET_MUSIC_MENU_FAIL = 'GET_MUSIC_MENU_FAIL';

export const REFRESH_MUSIC_MENU = 'REFRESH_MUSIC_MENU'
export const REFRESH_MUSIC_MENU_SUCCESS = 'REFRESH_MUSIC_MENU_SUCCESS'
export const REFRESH_MUSIC_MENU_FAIL = 'REFRESH_MUSIC_MENU_FAIL'