export const GET_ROOM_LIST = 'GET_ROOM_LIST'
export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS'
export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL'

export const REFRESH_ROOM_LIST = 'REFRESH_ROOM_LIST'
export const REFRESH_ROOM_LIST_SUCCESS = 'REFRESH_ROOM_LIST_SUCCESS'
export const REFRESH_ROOM_LIST_FAIL = 'REFRESH_ROOM_LIST_FAIL'

export const RESET_ROOM_LIST = 'RESET_ROOM_LIST'
export const UPDATE_ROOM_BY_ID = 'UPDATE_ROOM_BY_ID'