export const GET_ROOM_LIST = 'GET_ROOM_LIST'
export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS'
export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL'

export const REST_ROOM_LIST = 'REST_ROOM_LIST'
