export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAIL = 'GET_MY_PROFILE_FAIL';

export const EDIT_PROFILE_PHOTO = 'EDIT_PROFILE_PHOTO';
export const EDIT_PROFILE_PHOTO_SUCCESS = 'EDIT_PROFILE_PHOTO_SUCCESS';
export const EDIT_PROFILE_PHOTO_FAIL = 'EDIT_PROFILE_PHOTO_FAIL';

export const EDIT_COVER_PHOTO = 'EDIT_COVER_PHOTO';
export const EDIT_COVER_PHOTO_SUCCESS = 'EDIT_COVER_PHOTO_SUCCESS';
export const EDIT_COVER_PHOTO_FAIL = 'EDIT_COVER_PHOTO_FAIL';