export const GET_MY_FAV_MUSIC = 'GET_MY_FAV_MUSIC'
export const GET_MY_FAV_MUSIC_SUCCESS = 'GET_MY_FAV_MUSIC_SUCCESS'
export const GET_MY_FAV_MUSIC_FAIL = 'GET_MY_FAV_MUSIC_FAIL'

export const FILE_CACHE_IN_PROGRESS = 'FILE_CACHE_IN_PROGRESS'
export const FILE_CACHE_SUCCEEDED = 'FILE_CACHE_SUCCEEDED'
export const FILE_CACHE_FAILED = 'FILE_CACHE_FAILED'

export const REMOVE_FILE_IN_CACHE = 'REMOVE_FILE_IN_CACHE'
export const REMOVE_ALL_FILE_IN_CACHE = 'REMOVE_ALL_FILE_IN_CACHE'