export const GET_MY_FAV_MUSIC = 'GET_MY_FAV_MUSIC'
export const GET_MY_FAV_MUSIC_SUCCESS = 'GET_MY_FAV_MUSIC_SUCCESS'
export const GET_MY_FAV_MUSIC_FAIL = 'GET_MY_FAV_MUSIC_FAIL'

export const SET_MUSIC_FAV_IN_CACHE = 'SET_MUSIC_FAV_IN_CACHE'