export const GET_MY_FAV_MUSIC = 'GET_MY_FAV_MUSIC'
export const GET_MY_FAV_MUSIC_SUCCESS = 'GET_MY_FAV_MUSIC_SUCCESS'
export const GET_MY_FAV_MUSIC_FAIL = 'GET_MY_FAV_MUSIC_FAIL'

export const SET_MUSIC_FAV_IN_CACHE = 'SET_MUSIC_FAV_IN_CACHE'
export const SET_MUSIC_FAV_IN_CACHE_SUCCESS = 'SET_MUSIC_FAV_IN_CACHE_SUCCESS'
export const SET_MUSIC_FAV_IN_CACHE_FAIL = 'SET_MUSIC_FAV_IN_CACHE_FAIL'

export const ADD_MUSIC_AFTER_LIKED = 'ADD_MUSIC_AFTER_LIKED'
export const PULL_MUSIC_AFTER_DISLIKED = 'PULL_MUSIC_AFTER_DISLIKED'

export const RESET_MUSIC_CACHE = 'RESET_MUSIC_CACHE'

export const START_OF_UPLOAD = 'START_OF_UPLOAD'
export const END_OF_UPLOAD = 'END_OF_UPLOAD'