export const GET_COMMENT_LIST = 'GET_COMMENT_LIST'
export const GET_COMMENT_LIST_SUCCESS = 'GET_COMMENT_LIST_SUCCESS'
export const GET_COMMENT_LIST_FAIL = 'GET_COMMENT_LIST_FAIL'

export const GET_REPONSE_LIST = 'GET_RESPONSE_LIST'
export const GET_REPONSE_LIST_SUCCESS = 'GET_RESPONSE_LIST_SUCCESS'
export const GET_REPONSE_LIST_FAIL = 'GET_RESPONSE_LIST_FAIL'

export const SEND_COMMENT = 'SEND_COMMENT'
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL'

export const SEND_ANSWER = 'SEND_ANSWER'
export const SEND_ANSWER_SUCCESS = 'SEND_ANSWER_SUCCESS'
export const SEND_ANSWER_FAIL = 'SEND_ANSWER_FAIL'

export const LIKE_COMMENT = 'LIKE_COMMENT'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL'

export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'
export const UNLIKE_COMMENT_SUCCESS = 'UNLIKE_COMMENT_SUCCESS'
export const UNLIKE_COMMENT_FAIL = 'UNLIKE_COMMENT_FAIL'

export const LIKE_RESPONSE = 'LIKE_RESPONSE'
export const LIKE_RESPONSE_SUCCESS = 'LIKE_RESPONSE_SUCCESS'
export const LIKE_RESPONSE_FAIL = 'LIKE_RESPONSE_FAIL'

export const UNLIKE_RESPONSE = 'UNLIKE_RESPONSE'
export const UNLIKE_RESPONSE_SUCCESS = 'UNLIKE_RESPONSE_SUCCESS'
export const UNLIKE_RESPONSE_FAIL = 'UNLIKE_RESPONSE_FAIL'

export const RESET_COMMENT_LIST = 'RESET_COMMENT_LIST'
