export const GET_MUSIC_PLAYLIST = 'GET_MUSIC_PLAYLIST';
export const GET_MUSIC_PLAYLIST_SUCCESS = 'GET_MUSIC_PLAYLIST_SUCCESS';
export const GET_MUSIC_PLAYLIST_FAIL = 'GET_MUSIC_PLAYLIST_FAIL';
export const RESET_MUSIC_PLAYLIST = 'RESET_MUSIC_PLAYLIST';
