export const GET_MY_STORY = 'GET_MY_STORY'
export const GET_MY_STORY_SUCCESS = 'GET_MY_STORY_SUCCESS'
export const GET_MY_STORY_FAIL = 'GET_MY_STORY_FAIL'

export const DELETE_STORY_BY_ID = 'DELETE_STORY_BY_ID'
export const DELETE_STORY_BY_ID_SUCCESS = 'DELETE_STORY_BY_ID_SUCCESS'
export const DELETE_STORY_BY_ID_FAIL = 'DELETE_STORY_BY_ID_FAIL'



