export const GET_LIST_PUBLICATIONS_MUSIC = 'GET_LIST_PUBLICATIONS_MUSIC';
export const GET_LIST_PUBLICATIONS_MUSIC_SUCCESS = 'GET_LIST_PUBLICATIONS_MUSIC_SUCCESS';
export const GET_LIST_PUBLICATIONS_MUSIC_FAIL = 'GET_LIST_PUBLICATIONS_MUSIC_FAIL';
export const RESET_PUBLICATIONS_MUSIC = 'RESET_LIST_PUBLICATIONS_MUSIC';
